### ISSUE TITLE
Support dotty

### ISSUE THREAD

**Issue by thesamet** [monix/minitest#16]
I'm trying to use minitest on a project that is cross-compiled with dotty. I'm using minitest 2.1.1 using `withDottyCompat` so it picks up the 2.12 artifact.

I am getting the following compilation error at runtime:
```
[error] java.lang.NoSuchMethodError: minitest.api.SourceLocation$.fromContext()Lminitest/api/SourceLocation;
[error] 	at scalapb.lenses.SimpleTest$.$init$$$anonfun$1(SimpleTest.scala:82)
[error] 	at minitest.SimpleTestSuite.$anonfun$test$1(SimpleTestSuite.scala:27)
[error] 	at minitest.api.TestSpec$.$anonfun$sync$1(TestSpec.scala:51)
[error] 	at minitest.api.TestSpec.apply(TestSpec.scala:27)
[error] 	at minitest.api.Properties.$anonfun$iterator$2(Properties.scala:38)
[error] 	at minitest.api.TestSpec.apply(TestSpec.scala:27)
[error] 	at minitest.runner.Task.loop$1(Task.scala:40)
[error] 	at minitest.runner.Task.$anonfun$execute$4(Task.scala:55)
```

**Comment by thesamet** [comment]
Would it be possible, for the time being, to have a build for dotty with a non-macro implementation that  returns a default instance of `SourceLocation`? Happy to send a PR.

**Comment by olafurpg** [comment]
I guess an alternative solution is to return a constant `SourceLocation` in Dotty with hardcoded dummy values.

Cross-building should be fairly simple, `addSbtPlugin(sbt-dotty)` and `++0.8.0-RC1` should do the trick. Keep in mind a new Dotty version is released every ~6 weeks.

**Comment by olafurpg** [comment]
cc/ @nicolasstucki is working on the new metaprogramming system in Dotty and I think there will soon be available something equivalent to `__FILE__` and `__LINE__`. He can say more about the current status

**Comment by nicolasstucki** [comment]
I have some prototype implementations that provide line numbers 
* https://github.com/lampepfl/dotty/tree/master/tests/run/tasty-linenumber
* https://github.com/lampepfl/dotty/tree/master/tests/run/tasty-positioned

I do not have the file, but it would be trivial to add it to the API. It would be something similar to 
https://github.com/lampepfl/dotty/blob/master/tests/run/tasty-location/quoted_1.scala
but where we have `ctx.file` instead of `ctx.owner`.
