### ISSUE TITLE
Publish for Scala Native 0.4.0-M2

### ISSUE THREAD

**Issue by lolgab** [monix/minitest#46]
The PR I made makes it possible, you only need to launch sbt with the environment variable set:
```scala
SCALANATIVE_VERSION="0.4.0-M2" sbt
```

**Comment by ekrich** [comment]
It would be really nice to get both Scala Native `0.4.0-M2` support and Scala.js `1.0.0-RC1` support. Even though these are not production versions yet, downstream libraries need to release for these in order to flush out any issues and create a good environment for these new releases.

See https://github.com/monix/minitest/issues/43 for Scala.js

**Comment by Avasil** [comment]
`2.8.2` release should be available for `0.4.0-M2` let me know if there are any isseus

**Comment by lolgab** [comment]
Thank you for publishing. I'm closing this issue.
